#!/bin/bash

source ${VIRTUAL_ENV}/bin/activate

cd ${OPENSHIFT_REPO_DIR}wsgi/Uragan
#pip install -r requirements.txt

Commands[1]="migrate"
Commands[2]="collectstatic --noinput"
Commands[3]="makemessages --all"
Commands[4]="makemessages --domain=djangojs --all"
Commands[5]="compilemessages"


for index in 1 2 3 4 5
do
    echo "--------------------------------------------------------------------------------------"
    echo "python manage.py ${Commands[index]}"
    python manage.py ${Commands[index]}
    echo "--------------------------------------------------------------------------------------"
    echo ""
done
