#!/usr/bin/env python

from os import path, environ
from sys import path as sys_path

# GETTING-STARTED: make sure the next line points to your django project dir:
sys_path.append(path.join(environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'Uragan'))

environ.setdefault("DJANGO_SETTINGS_MODULE", "apps.common.settings")

venv = environ['VIRTUAL_ENV']

environ['PYTHON_EGG_CACHE'] = path.join(venv,
                                        'lib',
                                        'python{}'.format(environ['OPENSHIFT_PYTHON_VERSION']),
                                        'site-packages')

virtualenv = path.join(venv, 'bin', 'activate')

try:
    exec(compile(open(virtualenv).read(), virtualenv, 'exec'), dict(__file__=virtualenv))
except:
    pass

from django.core.wsgi import get_wsgi_application

application = get_wsgi_application()