#!/bin/bash
# .openshift/cron/minutely/update_TLE

MIN=$(date '+%M')
source ${VIRTUAL_ENV}/bin/activate
cd ${OPENSHIFT_REPO_DIR}wsgi/Uragan

let "GO = MIN % 15"

if [ $GO == 0 ]; then
    echo "Start update TLE script."
    echo "Date and time: $(date -u)"
    python manage.py init_TLE
fi

exit